# Information on how to build this action
# https://www.andreasnesheim.no/setting-up-ci-for-your-net-maui-windows-app-with-github-actions/
# https://www.youtube.com/watch?v=8lvdLa0v8zY
# https://github.com/dotnet/maui/issues/16696

name: build for Windows

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui
    
    - name: Decrypt PFX File
      run: |
        echo "${{ secrets.WINDOWS_PFX_FILE }}" > cert.pfx.asc
        certutil -decode cert.pfx.asc cert.pfx
    - name: Add Cert to Store
      run: certutil -user -q -p ${{ secrets.WINDOWS_PFX_PASSWORD }} -importpfx cert.pfx NoRoot
      
    - name: Update software version
      run: |
        echo "using this build number as minor version: ${{ github.run_number }}"
        sed -i 's/>0.0.1</>1.0.0.${{ github.run_number }}</g'  code\Blast\Blast.csproj 
        cat code\Blast\Blast.csproj
        sed -i 's/0.0.1/1.0.0.${{ github.run_number }}/g'  code\Blast.Model\Services\Current.cs 
        cat code\Blast.Model\Services\Current.cs
        
    - name: Build
      #run: dotnet publish code/Blast/Blast.sln -c Release -f:net7.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="${{ secrets.WINDOWS_PFX_THUMBPRINT }}"
      run: dotnet publish code/Blast/Blast.csproj -c Release -f:net7.0-windows10.0.19041.0 /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="${{ secrets.WINDOWS_PFX_THUMBPRINT }}"
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: .\**\AppPackages\**\*.* 
    
